Repository UKHomeOffice/hocs-workflow, pull requests merged in 2022-05, with the labels that each got.

#704 HOCS-5027: add dependabot GitHub Action update
  .github/dependabot.yml
Labels: skip-release

#703 HOCS-5000: stage duplication problem
  src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/application/LogEvent.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/CreateCaseworkStageRequest.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/RecreateCaseworkStageRequest.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/CreateCaseworkStageRequestTest.java
Labels: patch

#711 HOCS-5021: Merge BF triage screens
  src/main/resources/processes/BF2_TRIAGE.bpmn
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: minor

#702 HOCS-4951: offline transfer notes and flow fix
  src/main/resources/processes/BF.bpmn
  src/main/resources/processes/BF2.bpmn
  src/main/resources/processes/BF2_TRIAGE.bpmn
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: minor

#713 HOCS-5024: BF add draft reject option
  src/main/resources/processes/BF.bpmn
  src/main/resources/processes/BF2.bpmn
  src/main/resources/processes/BF2_DRAFT.bpmn
  src/main/resources/processes/BF_DRAFT.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_DRAFT.java
Labels: minor

#712 HOCS-5026: integrate ex-gratia into triage BF&BF2
  src/main/resources/processes/BF2_TRIAGE.bpmn
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: minor

#718 Chore: Upgrade drone build image versions
  .drone.yml
Labels: skip-release

#719 HOCS-5032: Upgrade docker-compose and drone to use postgres 14
  .drone.yml
  docker-compose.yml
Labels: skip-release

#720 HOCS-5140: Add G-Action Slack failure notification
  .github/workflows/semver.yml
Labels: skip-release
