Repository UKHomeOffice/hocs-workflow, pull requests merged in 2022-08, with the labels that each got.

#745 HOCS-4943: support draft case closure
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Labels: minor

#746 HOCS-5391: fix internal gro team transfer
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
Labels: patch

#751 HOCS-5433: fix draft case closure note
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Labels: patch

#749 HOCS-5428: Fix POGR2 escalation
  src/main/resources/processes/POGR2/POGR2.bpmn
  src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn
Labels: minor

#753 HOCS-5363: remove POGR registration backwards func
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Labels: patch

#754 HOCS-4804: POGR2 add correspondents
  src/main/resources/processes/POGR2/POGR2.bpmn
  src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Labels: minor

#752 🧱 HOCS-5438: Support multi arch builds
  Dockerfile
Labels: minor, smoketest

#755 HOCS-5456: fix BF triage payment null exception
  src/main/resources/processes/BF/BF_TRIAGE.bpmn
  src/main/resources/processes/BF2/BF2_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf/BF_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf2/BF2_TRIAGE.java
Labels: patch

#761 HOCS-5471: correct team look up
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
Labels: patch

#762 HOCS-5469: rework case closure
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_GRO_INVESTIGATION.bpmn
  src/main/resources/processes/POGR/POGR_HMPO.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn
  src/main/resources/processes/POGR/SHARED/POGR_CLOSE_CASE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_CLOSE_CASE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_INVESTIGATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_INVESTIGATION.java
Labels: minor

#766 HOCS-5029: add POGR2 GRO Data Input
  src/main/resources/processes/POGR/GRO/POGR_GRO_PRIORITY_CHANGE_SCREEN.bpmn
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_PRIORITY_CHANGE_SCREEN.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Labels: minor

#769 HOCS-5031: POGR2 interim letters
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Labels: minor

#772 HOCS-5033: GRO allocation stage 2
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Labels: minor

#773 HOCS-5035: add POGR Stage 2 Investigation
  src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn
  src/main/resources/processes/POGR2/POGR2_GRO_INVESTIGATION.bpmn
  src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_INVESTIGATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_INVESTIGATION.java
Labels: minor

#775 HOCS-5511: Use new faster pipelines
  Dockerfile
Labels: patch

#777 HOCS-5042: Add POGR2 QA stage
  src/main/resources/processes/POGR/POGR_GRO_QA.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_QA.bpmn
  src/main/resources/processes/POGR2/POGR2_GRO_QA.bpmn
  src/main/resources/processes/POGR2/POGR2_HMPO_QA.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_QA.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_QA.java
Labels: minor

#779 HOCS-5526: add Stage 2 escalation process
  src/main/resources/processes/POGR/POGR_GRO_ESCALATE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_ESCALATE.bpmn
  src/main/resources/processes/POGR2/POGR2_GRO_ESCALATE.bpmn
  src/main/resources/processes/POGR2/POGR2_HMPO_ESCALATE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_ESCALATE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_ESCALATE.java
Labels: minor

#782 Alter maxUnavailable to 0 based on prod experience
  kube/kd/deployment.yaml
Labels: patch
