Repository UKHomeOffice/hocs-workflow, pull requests merged in 2022-03, with the labels that each got.

#654 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
Labels: major

#656 HOCS-4749: add linting/dry-run drone pipeline
  kube/.drone.yml
  kube/deploy.sh
Labels: patch

#658 Fix/hocs 4751 bf bf2 triage back links
  src/main/resources/processes/BF2_TRIAGE.bpmn
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/diffs/BF_TRIAGE-BF2_TRIAGE.diff
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: patch

#657 Feature/hocs 4718 to add realloc reason text area
  src/main/resources/processes/TO_CHANGE_BUSINESS_AREA.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_CHANGE_BUSINESS_AREA.java
Labels: minor

#660 HOCS-4599: create blank POGR workflow
  src/main/resources/processes/POGR/POGR.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java
Labels: minor

#653 HOCS-4576: update ex-gratia when closed
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
Labels: minor

#662 HOCS-4627: workflow for business area assigning
  src/main/resources/processes/POGR/POGR.bpmn
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Labels: minor

#659 HOCS-4761 add fix to allow case to move correctly from QA and Draft
  src/main/resources/processes/TO_DRAFT.bpmn
  src/main/resources/processes/TO_QA.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_QA.java
Labels: minor

#666 HOCS-4696: Override Dependabot labels
  .github/dependabot.yml
Labels: patch

#665 HOCS-4696: Remove duplicate Sonar Run.
  .drone.yml
Labels: patch

#661 HOCS-4698: Fix BF2 complaint input back button
  src/main/resources/processes/BF2_REGISTRATION.bpmn
  src/test/diffs/BF_REGISTRATION-BF2_REGISTRATION.diff
Labels: minor

#669 HOCS-4631: support sending interim letter
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Labels: minor

#670 HOCS-4632: support GRO triaging allocation
  src/main/resources/processes/POGR/POGR.bpmn
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Labels: minor

#652 HOCS-4221: Add ability to transfer BF cases to SMC
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/diffs/BF_TRIAGE-BF2_TRIAGE.diff
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: minor

#671 HOCS-4799: update build image
  .drone.yml
Labels: patch

#673 HOCS-4808: support tagging on support branches
  .drone.yml
Labels: patch

#664 Feature/hocs 3736 update foi teams and groups
  src/main/resources/processes/FOI.bpmn
  src/main/resources/processes/FOI_ACCEPTANCE.bpmn
  src/main/resources/processes/FOI_ALLOCATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/foi/FOI_ACCEPTANCE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/foi/FOI_ALLOCATION.java
Labels: minor

#674 HOCS-4633: POGR triage acceptance
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
Labels: minor

#675 HOCS-4630: support priority change
  src/main/resources/processes/POGR/GRO/POGR_GRO_PRIORITY_CHANGE_SCREEN.bpmn
  src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_PRIORITY_CHANGE_SCREEN.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Labels: minor

#676 HOCS-4634: add Investigation process flow
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
Labels: minor
