Repository UKHomeOffice/hocs-workflow, pull requests merged in 2022-04, with the labels that each got.

#682 HOCS-4636: POGR draft stage
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Labels: minor

#683 HOCS-4635: POGR telephone response flow
  src/main/resources/processes/POGR/POGR_GRO.bpmn
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn
  src/main/resources/processes/POGR/POGR_HMPO.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn
  src/main/resources/processes/POGR/SHARED/POGR_TELEPHONE_RESPONSE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_TELEPHONE_RESPONSE.java
Labels: minor

#688 HOCS-4635: change the telephone flow to use radio
  src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn
  src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Labels: patch

#689 HOCS-4863: update semver tag action release version
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#694 Hocs-4407: Update camunda to 7.16
  build.gradle
Labels: patch

#697 Remove db initialise initcontainer
  kube/kd/deployment.yaml
Labels: patch

#699 HOCS-3780: Remove diff based tests for workflows
  build.gradle
  src/test/diffs/BF-BF2.diff
  src/test/diffs/BF_DRAFT-BF2_DRAFT.diff
  src/test/diffs/BF_ESCALATE-BF2_ESCALATE.diff
  src/test/diffs/BF_QA-BF2_QA.diff
  src/test/diffs/BF_REGISTRATION-BF2_REGISTRATION.diff
  src/test/diffs/BF_SEND-BF2_SEND.diff
  src/test/diffs/BF_TRIAGE-BF2_TRIAGE.diff
  src/test/diffs/COMP-COMP2.diff
  src/test/diffs/COMP_CCH_REOPENED-COMP2_CCH_REOPENED.diff
  src/test/diffs/COMP_CCH_RETURNS-COMP2_CCH_RETURNS.diff
  src/test/diffs/COMP_CLOSE-COMP2_CLOSE.diff
  src/test/diffs/COMP_CLOSED-COMP2_CLOSED.diff
  src/test/diffs/COMP_EXGRATIA_ESCALATE-COMP2_EXGRATIA_ESCALATE.diff
  src/test/diffs/COMP_EXGRATIA_QA-COMP2_EXGRATIA_QA.diff
  src/test/diffs/COMP_EXGRATIA_RESPONSE_DRAFT-COMP2_EXGRATIA_RESPONSE_DRAFT.diff
  src/test/diffs/COMP_EXGRATIA_SEND-COMP2_EXGRATIA_SEND.diff
  src/test/diffs/COMP_EXGRATIA_TRIAGE-COMP2_EXGRATIA_TRIAGE.diff
  src/test/diffs/COMP_MINORMISCONDUCT_ESCALATE-COMP2_MINORMISCONDUCT_ESCALATE.diff
  src/test/diffs/COMP_MINORMISCONDUCT_QA-COMP2_MINORMISCONDUCT_QA.diff
  src/test/diffs/COMP_MINORMISCONDUCT_RESPONSE_DRAFT-COMP2_MINORMISCONDUCT_RESPONSE_DRAFT.diff
  src/test/diffs/COMP_MINORMISCONDUCT_SEND-COMP2_MINORMISCONDUCT_SEND.diff
  src/test/diffs/COMP_MINORMISCONDUCT_TRIAGE-COMP2_MINORMISCONDUCT_TRIAGE.diff
  src/test/diffs/COMP_MINOR_CHECK-COMP2_MINOR_CHECK.diff
  src/test/diffs/COMP_MINOR_RESP-COMP2_MINOR_RESP.diff
  src/test/diffs/COMP_OTHER-COMP2_OTHER.diff
  src/test/diffs/COMP_REGISTRATION-COMP2_REGISTRATION.diff
  src/test/diffs/COMP_SERVICE_DRAFT-COMP2_SERVICE_DRAFT.diff
  src/test/diffs/COMP_SERVICE_ESCALATE-COMP2_SERVICE_ESCALATE.diff
  src/test/diffs/COMP_SERVICE_QA-COMP2_SERVICE_QA.diff
  src/test/diffs/COMP_SERVICE_SEND-COMP2_SERVICE_SEND.diff
  src/test/diffs/COMP_SERVICE_TRIAGE-COMP2_SERVICE_TRIAGE.diff
  src/test/scripts/check_BF_BF2.sh
  src/test/scripts/check_COMP_COMP2.sh
  src/test/scripts/diff_BF_BF2.sh
  src/test/scripts/diff_COMP_COMP2.sh
Labels: skip-release

#698 HOCS-4951: implement temp case transfer solution BF & BF2
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowConstants.java
  src/main/resources/processes/BF2_TRIAGE.bpmn
  src/main/resources/processes/BF_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF2_TRIAGE.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_TRIAGE.java
Labels: minor
