Repository UKHomeOffice/hocs-workflow, pull requests merged in 2022-09, with the labels that each got.

#783 HOCS-5547: update expression
  src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn
  src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_INVESTIGATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_INVESTIGATION.java
Labels: patch

#784 HOCS-5534: IEDET registration changes
  src/main/resources/processes/IEDET/IEDET.bpmn
  src/main/resources/processes/IEDET/IEDET_DRAFT.bpmn
  src/main/resources/processes/IEDET/IEDET_REGISTRATION.bpmn
  src/main/resources/processes/IEDET/IEDET_SEND.bpmn
  src/main/resources/processes/IEDET/IEDET_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_DRAFT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_REGISTRATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_SEND.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_TRIAGE.java
Labels: minor

#787 HOCS-5571: add back flow
  src/main/resources/processes/POGR/SHARED/POGR_TELEPHONE_RESPONSE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_TELEPHONE_RESPONSE.java
Labels: patch

#785 HOCS-2239: Remove redundant certs container
  kube/kd/deployment.yaml
Labels: patch

#788 HOCS-4815: Add IEDET assign screen
  src/main/resources/processes/IEDET/IEDET.bpmn
  src/main/resources/processes/IEDET/IEDET_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_TRIAGE.java
Labels: minor

#790 HOCS-5512: IEDET capture additional Complaint Details
  src/main/resources/processes/IEDET/IEDET_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_REGISTRATION.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_TRIAGE.java
Labels: minor

#794 HOCS-5596: Support PSU escalation
  src/main/resources/processes/IEDET/IEDET.bpmn
  src/main/resources/processes/PSU/PSU.bpmn
  src/main/resources/processes/PSU/PSU_COMPLAINT.bpmn
  src/main/resources/processes/PSU/PSU_OUTCOME.bpmn
  src/main/resources/processes/PSU/PSU_REGISTRATION.bpmn
  src/main/resources/processes/PSU/PSU_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_COMPLAINT.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_REGISTRATION.java
Labels: minor

#797 HOCS-5635: IEDET Move transfer case note
  src/main/resources/processes/IEDET/IEDET_TRIAGE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_TRIAGE.java
Labels: minor

#798 HOCS-5612: POGR - Closure reason not displayed in timeline when the case is closed at Investigation stage
  src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java
  src/main/resources/processes/POGR/SHARED/POGR_CLOSE_CASE.bpmn
  src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_CLOSE_CASE.java
Labels: minor

#791 HOCS-5569: deprecate accordion calls
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetCaseDetailsResponse.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetCaseResponse.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/GetAllStagesForCaseResponse.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/InfoClient.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/domain/model/forms/HocsCaseSchema.java
Labels: minor, smoketest

#800 HOCS-5545: remove deprecated field summary
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/FieldDto.java
  src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/FieldDtoBuilder.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/api/FormServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
Labels: major
